CREATE TABLE UserRegistration(ID BIGINT PRIMARY KEY AUTO_INCREMENT, 
				  FBUYER VARCHAR(1), 
                  NAME VARCHAR(30), ADDRESS VARCHAR(100),
                  STATE VARCHAR(30), ZIPCODE VARCHAR(10),
                  SSN VARCHAR(9), JOBTIME BIGINT,
                  PAYFREQUENCY BIGINT, REASON VARCHAR(100),
                  COSIGNER VARCHAR(1),
                  C_NAME VARCHAR(30), C_ADDRESS VARCHAR(100),
                  C_STATE VARCHAR(30), C_ZIPCODE VARCHAR(10),
                  C_SSN VARCHAR(9), C_JOBTIME BIGINT,
                  C_PAYFREQUENCY BIGINT
                 );
                 
CREATE TABLE UserLoanInformation(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
				USER_ID BIGINT, PAYMENT_RANGE_MIN BIGINT,
				PAYMENT_RANGE_MAX BIGINT, STATE VARCHAR(30),
				ZIPCODE VARCHAR(10), VEHICLE_YEAR BIGINT,
				VEHICLE_MILAGE BIGINT, VEHICLE_BOOK_VALUE VARCHAR(20),
				TRADEIN VARCHAR(1), TRADEIN_AMOUNT_OWNED VARCHAR(20),
				TRADEIN_AMOUNT_TO_CREDIT VARCHAR(20), LOAN_TERM_LENGTH BIGINT);